/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author juans
 */
public class Calculadora extends javax.swing.JFrame {
    private String cadena_numeros = "";
    private String operacion = "nula";
    private double primer_numero, resultado;
    private boolean activado = true;
    private boolean punto = true;
    private double epsilon = 1e-10;
    private boolean entero = false;
    
    
    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_c = new javax.swing.JButton();
        boton_raiz = new javax.swing.JButton();
        boton_division = new javax.swing.JButton();
        boton_ce = new javax.swing.JButton();
        boton_siete = new javax.swing.JButton();
        boton_ocho = new javax.swing.JButton();
        boton_nueve = new javax.swing.JButton();
        boton_multiplicacion = new javax.swing.JButton();
        boton_cuatro = new javax.swing.JButton();
        boton_cinco = new javax.swing.JButton();
        boton_seis = new javax.swing.JButton();
        boton_menos = new javax.swing.JButton();
        boton_uno = new javax.swing.JButton();
        boton_dos = new javax.swing.JButton();
        boton_tres = new javax.swing.JButton();
        boton_mas = new javax.swing.JButton();
        boton_menos_barra_mas = new javax.swing.JButton();
        boton_cero = new javax.swing.JButton();
        boton_coma = new javax.swing.JButton();
        boton_igual = new javax.swing.JButton();
        etiqueta_numeros = new javax.swing.JLabel();
        etiqueta_muestra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        boton_c.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_c.setText("C");
        boton_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cActionPerformed(evt);
            }
        });
        jPanel1.add(boton_c);

        boton_raiz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_raiz.setText("√ ");
        boton_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_raizActionPerformed(evt);
            }
        });
        jPanel1.add(boton_raiz);

        boton_division.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_division.setText("/");
        boton_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_divisionActionPerformed(evt);
            }
        });
        jPanel1.add(boton_division);

        boton_ce.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_ce.setText("CE");
        boton_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ceActionPerformed(evt);
            }
        });
        jPanel1.add(boton_ce);

        boton_siete.setBackground(new java.awt.Color(215, 215, 215));
        boton_siete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_siete.setForeground(new java.awt.Color(21, 32, 21));
        boton_siete.setText("7");
        boton_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sieteActionPerformed(evt);
            }
        });
        jPanel1.add(boton_siete);

        boton_ocho.setBackground(new java.awt.Color(215, 215, 215));
        boton_ocho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_ocho.setForeground(new java.awt.Color(21, 32, 21));
        boton_ocho.setText("8");
        boton_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ochoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_ocho);

        boton_nueve.setBackground(new java.awt.Color(215, 215, 215));
        boton_nueve.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_nueve.setForeground(new java.awt.Color(21, 32, 21));
        boton_nueve.setText("9");
        boton_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nueveActionPerformed(evt);
            }
        });
        jPanel1.add(boton_nueve);

        boton_multiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_multiplicacion.setText("X");
        boton_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_multiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(boton_multiplicacion);

        boton_cuatro.setBackground(new java.awt.Color(215, 215, 215));
        boton_cuatro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_cuatro.setForeground(new java.awt.Color(21, 32, 21));
        boton_cuatro.setText("4");
        boton_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cuatroActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cuatro);

        boton_cinco.setBackground(new java.awt.Color(215, 215, 215));
        boton_cinco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_cinco.setForeground(new java.awt.Color(21, 32, 21));
        boton_cinco.setText("5");
        boton_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cincoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cinco);

        boton_seis.setBackground(new java.awt.Color(215, 215, 215));
        boton_seis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_seis.setForeground(new java.awt.Color(21, 32, 21));
        boton_seis.setText("6");
        boton_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_seisActionPerformed(evt);
            }
        });
        jPanel1.add(boton_seis);

        boton_menos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_menos.setText("-");
        boton_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_menosActionPerformed(evt);
            }
        });
        jPanel1.add(boton_menos);

        boton_uno.setBackground(new java.awt.Color(215, 215, 215));
        boton_uno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_uno.setForeground(new java.awt.Color(21, 32, 21));
        boton_uno.setText("1");
        boton_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_unoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_uno);

        boton_dos.setBackground(new java.awt.Color(215, 215, 215));
        boton_dos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_dos.setForeground(new java.awt.Color(21, 32, 21));
        boton_dos.setText("2");
        boton_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_dosActionPerformed(evt);
            }
        });
        jPanel1.add(boton_dos);

        boton_tres.setBackground(new java.awt.Color(215, 215, 215));
        boton_tres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_tres.setForeground(new java.awt.Color(21, 32, 21));
        boton_tres.setText("3");
        boton_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tresActionPerformed(evt);
            }
        });
        jPanel1.add(boton_tres);

        boton_mas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_mas.setText("+");
        boton_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_masActionPerformed(evt);
            }
        });
        jPanel1.add(boton_mas);

        boton_menos_barra_mas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_menos_barra_mas.setText("+/-");
        boton_menos_barra_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_menos_barra_masActionPerformed(evt);
            }
        });
        jPanel1.add(boton_menos_barra_mas);

        boton_cero.setBackground(new java.awt.Color(215, 215, 215));
        boton_cero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_cero.setForeground(new java.awt.Color(21, 32, 21));
        boton_cero.setText("0");
        boton_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ceroActionPerformed(evt);
            }
        });
        jPanel1.add(boton_cero);

        boton_coma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_coma.setText(".");
        boton_coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_coma);

        boton_igual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_igual.setText("=");
        boton_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_igualActionPerformed(evt);
            }
        });
        jPanel1.add(boton_igual);

        etiqueta_numeros.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        etiqueta_numeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_numeros.setText("0");
        etiqueta_numeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        etiqueta_muestra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiqueta_muestra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta_muestra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
            .addComponent(etiqueta_numeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(etiqueta_muestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_muestra, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqueta_numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_raizActionPerformed
          if(activado == true){
            primer_numero = Double.parseDouble(cadena_numeros);
            etiqueta_muestra.setText("√" + primer_numero);
            cadena_numeros = "";
            operacion = "raiz";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_boton_raizActionPerformed

    private void boton_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_divisionActionPerformed
          if(activado == true){
            primer_numero = Double.parseDouble(cadena_numeros);
            etiqueta_muestra.setText(cadena_numeros + "/");
            cadena_numeros = "";
            operacion = "dividir";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_boton_divisionActionPerformed

    private void boton_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sieteActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "7";
        }else{
            cadena_numeros += "7";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_sieteActionPerformed

    private void boton_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ochoActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "8";
        }else{
            cadena_numeros += "8";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_ochoActionPerformed

    private void boton_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nueveActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "9";
        }else{
            cadena_numeros += "9";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_nueveActionPerformed

    private void boton_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cuatroActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "4";
        }else{
            cadena_numeros += "4";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_cuatroActionPerformed

    private void boton_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cincoActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "5";
        }else{
            cadena_numeros += "5";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_cincoActionPerformed

    private void boton_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_seisActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "6";
        }else{
            cadena_numeros += "6";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
        
    }//GEN-LAST:event_boton_seisActionPerformed

    private void boton_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_unoActionPerformed
       if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "1";
        }else{
            cadena_numeros += "1";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
        punto = true;
    }//GEN-LAST:event_boton_unoActionPerformed

    private void boton_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_dosActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "2";
        }else{
            cadena_numeros += "2";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_dosActionPerformed

    private void boton_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tresActionPerformed
        if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "3";
        }else{
            cadena_numeros += "3";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_tresActionPerformed

    private void boton_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_masActionPerformed

         if(activado == true){
            primer_numero = Double.parseDouble(cadena_numeros);
            etiqueta_muestra.setText(cadena_numeros + "+");
            cadena_numeros = "";
            operacion = "sumar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_boton_masActionPerformed

    private void boton_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_igualActionPerformed
        double segundo_numero;
        if(operacion.equals("nula")){
            etiqueta_numeros.setText(cadena_numeros);
        }else if(operacion.equals("sumar")){
            segundo_numero = Double.parseDouble(cadena_numeros);
            resultado = primer_numero + segundo_numero;
            entero = esEntero(resultado, epsilon);
            if(entero){
                 etiqueta_numeros.setText(String.format("% .0f", resultado));
            }
            cadena_numeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("multiplicar")){
            segundo_numero = Double.parseDouble(cadena_numeros);
            resultado = primer_numero * segundo_numero;
            entero = esEntero(resultado, epsilon);
            if(entero){
                 etiqueta_numeros.setText(String.format("% .0f", resultado));
            }
            cadena_numeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("dividir")){
            segundo_numero = Double.parseDouble(cadena_numeros);
            resultado = primer_numero / segundo_numero;
            entero = esEntero(resultado, epsilon);
            if(entero){
                 etiqueta_numeros.setText(String.format("% .0f", resultado));
            }
            cadena_numeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("restar")){
            segundo_numero = Double.parseDouble(cadena_numeros);
            resultado = primer_numero - segundo_numero;
            entero = esEntero(resultado, epsilon);
            if(entero){
                 etiqueta_numeros.setText(String.format("% .0f", resultado));
            }
            cadena_numeros = String.valueOf(resultado);
            operacion = "nula";
        }else if(operacion.equals("raiz")){
            resultado = Math.sqrt(primer_numero);
            entero = esEntero(resultado, epsilon);
            if(entero){
                 etiqueta_numeros.setText(String.format("% .0f", resultado));
            }
            cadena_numeros = String.valueOf(resultado);
            operacion = "nula";
        }
        
        etiqueta_muestra.setText("");
        activado = true;
    }//GEN-LAST:event_boton_igualActionPerformed

    private void boton_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_multiplicacionActionPerformed
         if(activado == true){
            primer_numero = Double.parseDouble(cadena_numeros);
            etiqueta_muestra.setText(cadena_numeros + "X");
            cadena_numeros = "";
            operacion = "multiplicar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_boton_multiplicacionActionPerformed

    private void boton_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_menosActionPerformed
          if(activado == true){
            primer_numero = Double.parseDouble(cadena_numeros);
            etiqueta_muestra.setText(cadena_numeros + "-");
            cadena_numeros = "";
            operacion = "restar";
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_boton_menosActionPerformed

    private void boton_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ceroActionPerformed
         if(etiqueta_numeros.getText().equals("0")){
            cadena_numeros = "0";
        }else{
            cadena_numeros += "0";
        }
        etiqueta_numeros.setText(cadena_numeros);
        activado = true;
    }//GEN-LAST:event_boton_ceroActionPerformed

    private void boton_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cActionPerformed
        cadena_numeros = "";
        etiqueta_numeros.setText("");
        etiqueta_muestra.setText("");
        operacion = "nula";
        activado = true;
        punto = true;
    }//GEN-LAST:event_boton_cActionPerformed

    private void boton_comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comaActionPerformed
        if(punto == true){
            if(cadena_numeros.equals("")){
                cadena_numeros = "0.";
            }else{
                cadena_numeros += ".";  
            }
        }
        etiqueta_numeros.setText(cadena_numeros);
        punto = false;
    }//GEN-LAST:event_boton_comaActionPerformed

    private void boton_menos_barra_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_menos_barra_masActionPerformed
        if(cadena_numeros.charAt(0) != '-'){
            cadena_numeros = "-" + cadena_numeros;
        }else{
            cadena_numeros = cadena_numeros.substring(1, cadena_numeros.length());
        }
        etiqueta_numeros.setText(cadena_numeros);
    }//GEN-LAST:event_boton_menos_barra_masActionPerformed

    private void boton_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ceActionPerformed
        int tamanio = cadena_numeros.length();
        if(tamanio > 0){
            if(tamanio == 1){
                cadena_numeros = "0";
            }else{
                cadena_numeros = cadena_numeros.substring(0, cadena_numeros.length() - 1);
            }
        }
        etiqueta_numeros.setText(cadena_numeros);
    }//GEN-LAST:event_boton_ceActionPerformed
    
    public static boolean esEntero(double numero, double epsilon) {
        return Math.abs(numero - Math.round(numero)) < epsilon;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_c;
    private javax.swing.JButton boton_ce;
    private javax.swing.JButton boton_cero;
    private javax.swing.JButton boton_cinco;
    private javax.swing.JButton boton_coma;
    private javax.swing.JButton boton_cuatro;
    private javax.swing.JButton boton_division;
    private javax.swing.JButton boton_dos;
    private javax.swing.JButton boton_igual;
    private javax.swing.JButton boton_mas;
    private javax.swing.JButton boton_menos;
    private javax.swing.JButton boton_menos_barra_mas;
    private javax.swing.JButton boton_multiplicacion;
    private javax.swing.JButton boton_nueve;
    private javax.swing.JButton boton_ocho;
    private javax.swing.JButton boton_raiz;
    private javax.swing.JButton boton_seis;
    private javax.swing.JButton boton_siete;
    private javax.swing.JButton boton_tres;
    private javax.swing.JButton boton_uno;
    private javax.swing.JLabel etiqueta_muestra;
    private javax.swing.JLabel etiqueta_numeros;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
